### ISSUE TITLE
Implement Rate my game

### ISSUE THREAD

**Issue by ghost** [EvergineTeam/Samples-2.5#10]
HI,

Reviews are very important for a game or app..Even though you develop a cool and good game,but
if promotions are not there,then there is no value for the game.
So please implement the "Rate my game" functionality

**Comment by illanos** [comment]
hi @tonyyyrocks39 !!

Thanks for the feedback, certainly rate my game is a feature should be included in the Game Center.

You can redirect your questions to https://forum.waveengine.net/ where we can attend you, also we have an user voice for request http://feedback.waveengine.net/forums/194963-general/filters/top

**Comment by pulimento** [comment]
Hello there,
We're focusing our support on [the forum](https://forums.waveengine.net). Please post questions there. I'm closing this issue now due to inactivity.
