### ISSUE TITLE
Samples throw many errors and won't run because wrong Microsoft.Build.Frameworks.dll

### ISSUE THREAD

**Issue by ghost** [EvergineTeam/Samples-2.5#11]
Hello everyone,

please fix I have many errors because I can not build successfully. Visual Studio 2017 throws always stupid dll Microsoft.Build.Frameworks.dll I already added repository for WaveEngine.

PS: I already tried to complete .. But no success

Why does Microsoft.Build.Framework not work for me :(

I am using Windows 10 Pro x64

**Comment by pulimento** [comment]
Hello there,
We're focusing our support on [the forum](https://forums.waveengine.net). Please post questions there. I'm closing this issue now due to inactivity.
