### ISSUE TITLE
Youtube Videos 360º with WaveEngine.Cardboard API

### ISSUE THREAD

**Issue by WiliamGP** [EvergineTeam/Samples-2.5#5]
Hello, I wonder if I can consume videos 360º from Youtube using WaveEngine.Cardboard API and where can I find examples of how to do this in applications for Windows 10 Mobile with C#.

Regards.

**Comment by WiliamGP** [comment]
Someone can help with this??

**Comment by mgomar** [comment]
Hi there!

Sorry for the delay, We can give you support at https://forum.waveengine.net/

**Comment by WiliamGP** [comment]
@mgomar Thank you, I will submit my questions in the forum. Best regards!

**Comment by pulimento** [comment]
Hello there,
We're focusing our support on [the forum](https://forums.waveengine.net). Please post questions there. I'm closing this issue now due to inactivity.
