### ISSUE TITLE
How to drag a sprite.

### ISSUE THREAD

**Issue by ghost** [EvergineTeam/Samples-2.5#6]
HI All,

Currently I am developing a small 2-d game with the help of these samples.
I am trying to drag a sprite along its X-position...

Could you please help me.....

**Comment by ghost** [comment]
Please help somebody

**Comment by mgomar** [comment]
Hi there!!
Sorry for the waiting!, Please for support go to https://forum.waveengine.net/ and there we will glad to help you with this drag and drop problem!

**Comment by ghost** [comment]
Ok ..I have fixed it..
