### ISSUE TITLE
Issue when building a HoloLens project...

### ISSUE THREAD

**Issue by soccermitchy** [EvergineTeam/Samples-2.5#7]
Wasn't sure what repository to put this in, but I'm getting this whenever I try to build a project using the HoloLens launcher (not sure if it affects other ones yet)

`1>C:\Users\Mitchell\.nuget\packages\WaveEngine\2.2.0.26\build\uap10.0\WaveEngine.targets(13,2): error MSB3073: The command ""v2.0\Tools\VisualEditor\WaveConstantsCMD.exe" -i "C:\Users\Mitchell\Documents\WaveEngineProjects\HoloTest\test\test.weproj" -o "C:\Users\Mitchell\Documents\WaveEngineProjects\HoloTest\test\SharedSource\Main"" exited with code 3.`

Looking into the msbuild files, it looked like the WaveEngine variable (guessing it contained the path to the WaveEngine files) was undefined, how would I go about defining it?

**Comment by mgomar** [comment]
Hi there!

for support please redirect to https://forum.waveengine.net/ and there we will try to resolve your problem!

**Comment by pulimento** [comment]
Hello there,
We're focusing our support on [the forum](https://forums.waveengine.net). Please post questions there. I'm closing this issue now due to inactivity.
