### ISSUE TITLE
For support redirect to Wave Engine Forum

### ISSUE THREAD

**Issue by mgomar** [EvergineTeam/Samples-2.5#8]
Hi there, you can ask all your questions and report problems in Wave Engine oficial forum https://forum.waveengine.net/ where we will try our best to give you a solution as fast as we can!.

**Comment by pulimento** [comment]
Hello there,
We're focusing our support on [the forum](https://forums.waveengine.net). Please post questions there. I'm closing this issue now due to inactivity.
