### ISSUE TITLE
Problem with run Samples.Exstentions in macOS

### ISSUE THREAD

**Issue by ximet** [EvergineTeam/Samples-2.5#9]
I have a problem with run build and run project in macOS 10.12.3 in Xamarin Studio 6.0:

For example, I started VuforiaTest_Android.sln and have Error:

`/MyPath/Samples-b00057faf3fb92837011f29a8e13dccb51c7b7fd/Extensions/VuforiaTest/packages/WaveEngine.2.3.0.29/build/MonoAndroid/WaveEngine.targets: Error: Command 'mono "WaveConstantsCMD.exe" -i "/MyPath/Samples-b00057faf3fb92837011f29a8e13dccb51c7b7fd/Extensions/VuforiaTest/VuforiaTest.weproj" -o "/MyPath/Samples-b00057faf3fb92837011f29a8e13dccb51c7b7fd/Extensions/VuforiaTest/SharedSource/Main"' exited with code: 255. (VuforiaTest)`

How resolve this problem?

**Comment by mgomar** [comment]
Hi there!

for support please redirect to https://forum.waveengine.net/ and there we will try to resolve your problem!

**Comment by ximet** [comment]
OK, thank you. Close issue, please
